# Test your FastAPI endpoints

POST http://127.0.0.1:8000/initdb
Accept: application/json

###

POST http://127.0.0.1:8000/api/v1/translate/user/1/subject/1
Content-Type: application/json
Accept: text/event-stream

{
  "input": "일련의 값들을 가지고 있는 자료구조를 구성할 때, 대부분 '슬라이스'를 사용한다.",
  "from_lang": "korean",
  "to_lang": "english"
}

###

POST http://127.0.0.1:8000/api/v1/translate/user/1/subject/1
Content-Type: application/json
Accept: text/event-stream

{
  "input": "It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends.",
  "from_lang": "english",
  "to_lang": "korean"
}

###

POST http://127.0.0.1:8000/api/v1/entity/user
Content-Type: application/json
Accept: application/json

{
  "name": "Isaac Park",
  "email": "merrygoroundof@naver.com"
}

###

GET http://127.0.0.1:8000/api/v1/entity/user/1
Accept: application/json

###

DELETE http://127.0.0.1:8000/api/v1/entity/user/1
Accept: application/json

###

POST http://127.0.0.1:8000/api/v1/entity/subject
Content-Type: application/json
Accept: application/json

{
  "topic": "Study English",
  "userId": 1
}

###

GET http://127.0.0.1:8000/api/v1/entity/subject/1
Accept: application/json

###

GET http://127.0.0.1:8000/api/v1/entity/subject?user_id=1
Accept: application/json

###

DELETE http://127.0.0.1:8000/api/v1/entity/subject/1
Accept: application/json

###
