# Test your FastAPI endpoints

POST http://127.0.0.1:8000/initdb
Accept: application/json

###

POST http://127.0.0.1:8000/api/v1/entity/user
Content-Type: application/json
Accept: application/json

{
  "name": "Isaac Park",
  "email": "merrygoroundof@naver.com"
}

###

POST http://127.0.0.1:8000/api/v1/entity/subject
Content-Type: application/json
Accept: application/json

{
  "topic": "Chat",
  "userId": 1
}

###

POST http://127.0.0.1:8000/api/v1/entity/subject
Content-Type: application/json
Accept: application/json

{
  "topic": "Translation",
  "systemRole": "a helpful translator",
  "promptTemplate": "Please translate from {from_lang} to {to_lang}:",
  "userId": 1
}

###

POST http://127.0.0.1:8000/api/v1/entity/subject
Content-Type: application/json
Accept: application/json

{
  "topic": "Git Commit Message",
  "systemRole": "an assistant that helps create git commit messages",
  "promptTemplate": "Please translate the following into a concise and accurate expression suitable for an English git commit message:",
  "userId": 1
}

###

POST http://127.0.0.1:8000/api/v1/chat/user/1/subject/1
Content-Type: application/json
Accept: text/event-stream

{
  "input": "시력이 나쁜 것과 난독증과 관련이 있을까?"
}

###

POST http://127.0.0.1:8000/api/v1/chat/user/1/subject/2
Content-Type: application/json
Accept: text/event-stream

{
  "params": {
    "from_lang": "korean",
    "to_lang": "english"
  },
  "input": "일련의 값들을 가지고 있는 자료구조를 구성할 때, 대부분 '슬라이스'를 사용한다."
}

###

POST http://127.0.0.1:8000/api/v1/chat/user/1/subject/2
Content-Type: application/json
Accept: text/event-stream

{
  "params": {
    "from_lang": "english",
    "to_lang": "korean"
  },
  "input": "It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends."
}

###

POST http://127.0.0.1:8000/api/v1/chat/user/1/subject/3
Content-Type: application/json
Accept: text/event-stream

{
  "input": "Prompt 를 Subject 정보를 참조하여 생성하도록 수정"
}

###
