# Test your FastAPI endpoints

POST http://127.0.0.1:8000/initdb
Accept: application/json

###

POST http://127.0.0.1:8000/api/v1/entity/group
Content-Type: application/json
Accept: application/json

{
  "name": "Plantrue Group",
  "email": "plantrue@kakao.com"
}

###

POST http://127.0.0.1:8000/api/v1/entity/user
Content-Type: application/json
Accept: application/json

{
  "name": "Isaac Park",
  "email": "merrygoroundof@naver.com",
  "groupId": 1
}

###

POST http://127.0.0.1:8000/api/v1/entity/subject
Content-Type: application/json
Accept: application/json

{
  "topic": "Chat",
  "ownerId": 1
}

###

POST http://127.0.0.1:8000/api/v1/entity/subject
Content-Type: application/json
Accept: application/json

{
  "topic": "Translation",
  "systemRole": "a helpful translator",
  "promptTemplate": "Please translate from {from_lang} to {to_lang}:",
  "ownerId": 1
}

###

POST http://127.0.0.1:8000/api/v1/entity/subject
Content-Type: application/json
Accept: application/json

{
  "topic": "Git Commit Message",
  "systemRole": "an assistant that helps create git commit messages",
  "promptTemplate": "Please translate the following into a concise and accurate expression suitable for an English git commit message:",
  "ownerId": 1
}

###

POST http://127.0.0.1:8000/api/v1/entity/subject
Content-Type: application/json
Accept: application/json

{
  "topic": "Paraphrase",
  "systemRole": "an assistant that helps paraphrase texts to match the requested level",
  "promptTemplate": "Please paraphrase the following text to match the CEFR {level} level:",
  "ownerId": 1
}

###

POST http://127.0.0.1:8000/api/v1/entity/subject
Content-Type: application/json
Accept: application/json

{
  "topic": "Grammar",
  "systemRole": "an assistant that explains English sentence structures grammatically",
  "promptTemplate": "Please explain the following sentence structure grammatically in Korean so that a CEFR {level} learner can understand it:",
  "ownerId": 1
}

###

PUT http://127.0.0.1:8000/api/v1/entity/group/1/subject/1
Accept: application/json

###

PUT http://127.0.0.1:8000/api/v1/entity/group/1/subject/2
Accept: application/json

###

PUT http://127.0.0.1:8000/api/v1/entity/group/1/subject/3
Accept: application/json

###

PUT http://127.0.0.1:8000/api/v1/entity/group/1/subject/4
Accept: application/json

###

PUT http://127.0.0.1:8000/api/v1/entity/group/1/subject/5
Accept: application/json

###

POST http://127.0.0.1:8000/api/v1/chat/user/1/subject/1
Content-Type: application/json
Accept: text/event-stream

{
  "input": "시력이 나쁜 것과 난독증과 관련이 있을까?"
}

###

POST http://127.0.0.1:8000/api/v1/chat/user/1/subject/2
Content-Type: application/json
Accept: text/event-stream

{
  "params": {
    "from_lang": "korean",
    "to_lang": "english"
  },
  "input": "일련의 값들을 가지고 있는 자료구조를 구성할 때, 대부분 '슬라이스'를 사용한다."
}

###

POST http://127.0.0.1:8000/api/v1/chat/user/1/subject/2
Content-Type: application/json
Accept: text/event-stream

{
  "params": {
    "from_lang": "english",
    "to_lang": "korean"
  },
  "input": "It takes a great deal of bravery to stand up to our enemies, but just as much to stand up to our friends."
}

###

POST http://127.0.0.1:8000/api/v1/chat/user/1/subject/3
Content-Type: application/json
Accept: text/event-stream

{
  "input": "Prompt 를 Subject 정보를 참조하여 생성하도록 수정"
}

###

POST http://127.0.0.1:8000/api/v1/chat/user/1/subject/4
Content-Type: application/json
Accept: text/event-stream

{
  "params":{
    "level": "A1"
  },
  "input": "A spokesperson for the Secret Service said in a statement Saturday that the agency has not provided certain resources in the past but has instead provided other security measures including from local partners. The news comes amid widespread concerns about how a sniper was able to obtain rooftop access roughly 150 meters from Trump’s position at an outdoor rally in Butler, Pennsylvania, last week."
}

###

POST http://127.0.0.1:8000/api/v1/chat/user/1/subject/5
Content-Type: application/json
Accept: text/event-stream

{
  "params":{
    "level": "A1"
  },
  "input": "The madder the Hulk gets, the stronger he gets."
}

###

POST http://127.0.0.1:8000/api/v1/chat/user/1/subject/5
Content-Type: application/json
Accept: text/event-stream

{
  "input": "madder 나 stronger 앞에 the 는 왜 붙는거야?",
  "without_prompt": true
}

###
